### ISSUE TITLE
Syntax extension to include one .fountain file from another

### ISSUE THREAD

**Issue by arikrupnik** [arikrupnik/fountainhead#6]

**Comment by overvale** [comment]
iA Writer’s [Content Blocks](https://github.com/iainc/Markdown-Content-Blocks) may be a good reference.

**Comment by arikrupnik** [comment]
This is an interesting idea. I like how they describe their thought process and how their desiderata lead to to their technical choices.

My initial thought on this took me in a different direction. I see including only one type of file, and no need for titles and additional metadata as you might with images, tables and source code. On the other hand, I like their boldness in introducing syntax that might interpret existing documents in backwards-incompatible ways.

How big of a deal is backward compatibility? My initial thinking was to piggy-back on synopsis or note syntax, e.g.:

    =<file.fountain

or

    [[<file.fountain]]

I was trying to avoid interpreting an existing .fountain file differently from its author's intent. I was also trying to avoid conflict with possible upcoming revisions of the fountain spec. Maybe these are smaller issues than I'm making them to be.

**Comment by overvale** [comment]
I think your syntax is great, and I totally agree that you should avoid conflicts with future spec changes (notes and synopsis nicely skirt that). But, please, don't require a ".fountain" extension.

In the future it might be nice to interpret metadata, for example you might want processing instructions specific to fountainhead.

**Comment by arikrupnik** [comment]
Are you saying you may want to include files of other types?

**Comment by arikrupnik** [comment]
@olivertaylor : check out this branch: https://github.com/arikrupnik/fountainhead/tree/includes and let me know how it looks to you.

**Comment by arikrupnik** [comment]
b3b4380 resolves this issue
